#!/bin/bash

# Update time and log to syslog
/usr/sbin/ntpdate -s 0.fedora.pool.ntp.org 1.fedora.pool.ntp.org 2.fedora.pool.ntp.org
# Write hardware clock, if available (virtual hosts might not have one)
/sbin/hwclock -w 2>/dev/null

